FORMAT: 1A
HOST: http://polls.neverbet.com/

# NeverBet
Документация по API 1.0 для мобильного приложения

# Group Матч-Центр
Информация о играх

## Список матчей [/games/{?date}]
Получение списка матчей на определенную дату. Если дата не указана, то список игр на сегодня

### Получение списка [GET]
+ Arguments
    + turnir:  (Turnir)
        + id: 21 (number) - ID турнира.
        + name: Примера (string) - название турнира
        + country: ES (string) - страна турнира
    + games:
        + id: 11 (number) - ID матча.
        + dtime: 2016.02.05 20:00:00 (DateTime) - время проведения матча в формате YY.mm.dd H:m:s (? timezone UTC).
        + status: wait (string) - wait, live, cancel, fin
        + info:
            + score: 3-2 (string) - счет матча
            + part: 2 (number) - тайм
            + minute: 86 (number) - минута матча
        + home: (Team) - первая команда
            + id: 22 (number) - ID команды.
            + name: Барселона (string) - название команды на русском.
            + logo: //img.neverbet.com/barcelona.png (string) -  ссылка на лого команды.
            + country: ES (string len=2) - IATA код страны команды.
            + cards - карточки
                + yellow: 2 (number) - желтые карты
                + red: 0 (number) - красные карты
            + corners: 2  (number) - угловые
        + guest: (Team) - вторая команда
            + id: 21 (number) - ID команды.
            + name: Рома (string) - название команды на русском.
            + logo: //img.neverbet.com/roma.png (string) -  ссылка на лого команды.
            + country: IT (string len=2) - IATA код страны команды.
            + cards - карточки
                + yellow: 2 (number) - желтые карты
                + red: 0 (number) - красные карты
            + corners: 2  (number) - угловые
        + odds - ставки / коэффициенты
            + P1 : 1.2 (float) - победа первой команды 
            + X: 2.2 (float) - ничья 
            + P2: 2.0 (float) - победа второй команды 
            + TOTAL: (Object)  - тотал
                "2.5": (Array[2]) - значение [больше чем значение, меньше чем значение] 
+ Parameters
    + date: 2016.04.15 (optional, string) - ID команды integer
+ Response 200 (application/json)

        [
            {
                "turnir": {
                    "id": 1,
                    "name": "Примера",
                    "country": "ES"
                },
                "games":[
                    {
                        "id": 11,
                        "dtime": "2016.02.05 20:00:00",
                        "status" : "live",
                        "info":{
                            "score": "3-0",
                            "part": 2,
                            "minute": 86
                        },
                        "home":{
                            "id": 22,
                            "name": "Барселона",
                            "country": "ES",
                            "cards":{
                                "yellow":2,
                                "red":0
                            },
                            "corners": 2
                        },
                        "guest": {
                            "id":21,
                            "name": "Рома",
                            "country": "ES",
                            "cards":{
                                "yellow":4,
                                "red":1
                            },
                            "corners": 12
                        },
                        "odds":{
                            "P1": 1.2,
                            "X": 2.2,
                            "P2": 2.0,
                            "TOTAL": {
                                "2.5":[1.2,3.2]
                            }
                        }
                    }
                ]
            }   
        ]

## Обзор матча [/game/{id}]
Информация по определенному матчу

### Описание матча [GET]
+ Arguments
    + turnir: 
        + id: 21 (number) - ID турнира.
        + name: Примера (string) - название турнира
        + country: ES (string) - страна турнира
    + games:
        + id: 11 (number) - ID матча.
        + dtime: 2016.02.05 20:00:00 (DateTime) - время проведения матча в формате YY.mm.dd H:m:s (? timezone UTC).
        + status: wait (string) - wait, live, cancel, fin
        + info:
            + score: 3-2 (string) - счет матча
            + part: 2 (number) - тайм
            + minute: 86 (number) - минута матча
            + place: Сюьдад де Валенсия (string) - стадион
            + judges: (Array) - судьи  матча
        + home: (Team) - первая команда
            + id: 22 (number) - ID команды.
            + name: Барселона (string) - название команды на русском.
            + logo: //img.neverbet.com/barcelona.png (string) -  ссылка на лого команды.
            + country: ES (string len=2) - IATA код страны команды.
            + cards - карточки
                + yellow: 2 (number) - желтые карты
                + red: 0 (number) - красные карты
            + corners: 2  (number) - угловые
        + guest: (Team) - вторая команда
            + id: 21 (number) - ID команды.
            + name: Рома (string) - название команды на русском.
            + logo: //img.neverbet.com/roma.png (string) -  ссылка на лого команды.
            + country: IT (string len=2) - IATA код страны команды.
            + cards - карточки
                + yellow: 2 (number) - желтые карты
                + red: 0 (number) - красные карты
            + corners: 2  (number) - угловые
        + odds - ставки / коэффициенты
            + P1 : 1.2 (float) - победа первой команды 
            + X: 2.2 (float) - ничья 
            + P2: 2.0 (float) - победа второй команды 
            + TOTAL: (Object)  - тотал
                "2.5": (Array[2]) - значение [больше чем значение, меньше чем значение] 
        + bets - статистика ставок
            + gamers: (Array) - мнение игроков
            + books: (Array) - мнение биукмеккров
            + stats: (Array) - мнение по статистике
        + text: (Array) - текстовая трансляция 
            + [минута, номер команды, событие, игрок]. События: SW-замена, YC-желтая карта, RC-красная карта, CR- угловой, GL-гол, PT-пенналти, AG-автогол,DN - удаление
        + feeds: (Array) - массив публикаций
            + id: 12 (number) - ID номер публикации 
            + author: (Author) - автор публикации
                + type: owner (string) - тип авторства: owner - владелец, repost - перепубликации
                + id: 12 (number) - ID автора
                + rate: 33 (number) - рейтинг авторa
                + name: Костян Филатов (string) - имя автора
                + thumb: "//img.neverbet.com/thumb/u56.jpg" (string) - адрес к аватарке пользователя
            + dtime: 2016.01.05 20:30 (DateTime) - дата и время публикации в формате Y.m.d H:m 
            + comments: 12 (number) - кол-во комментариев к публикации
            + rate: 3 (number) - рейтинг публикации
            + body: (string) - сообщение
            + tags: (Array) - массив тегов к публикации
+ Parameters
    + id: 11 (required, integer) - ID матча 
+ Response 200 (application/json)

        {
            "id": 11,
            "time": "2016.02.05 20:00:00",
            "status" : "live",
            "turnir": {
                "id": 1,
                "name": "Примера",
                "country": "ES"
            },
            "info":{
                "score": "3:2",
                "part": 2,
                "minute": 86,
                "place": "Сюьдад де Валенсия",
                "judges":[
                    "Карлос Веласко Карбальо"
                ]
            },
            "home":{
                "id": 22,
                "name": "Барселона",
                "country": "ES",
                "cards":{
                    "yellow":2,
                    "red":0
                },
                "corners": 2
            },
            "guest": {
                "id":21,
                "name": "Рома",
                "country": "ES",
                "cards":{
                    "yellow":4,
                    "red":1
                },
                "corners": 12
            },
            "odds":{
                "P1": 1.2,
                "X": 2.2,
                "P2": 2.0,
                "TOTAL": {
                    "2.5":[1.2,3.2]
                }
            },
            "bets":{
                "gamers":[
                    [75,"Барселона выиграет"],
                    [15,"Рома выиграет"],
                    [12,"Ничья"]
                ],
                "books":[
                    [75,"Победа первой"],
                    [55,"Тотал > 2.5"],
                    [23,"Ничья"]
                ],
                "stats":[
                    [75,"Барселона выиграет"],
                    [55,"Рома выиграет"],
                    [23,"Ничья"]
                ]
            },
            "text":[
                [79,2,"SW","Набиль Эль-Жар","Давид Симон"],
                [76,2,"SW","Серхио Араухо","Тана Домингес"],
                [75,1,"SW","Джузеппе Росси","Жорди Шуметра"],
                [74,1,"YC","Жорди Шуметра"],
                [66,2,"GL","Виллиан Жозе"]
            ],
            "feeds":[
                {
                    "id": 1235,
                    "author":{
                        "type":"owner",
                        "id":56,
                        "rate":33,
                        "name":"Костян Филатов",
                        "thumb":"//img.neverbet.com/user/u56.jpg"
                    },
                    "dtime": "2016.01.05 20:30",
                    "comments":12,
                    "rate":3,
                    "body":"<img src='//img.neverbet.com/feeds/u56sdf23gf.jpg'/>Русский форвард #Вашингтона оформил 14-й хет-трик за карьеру в НХЛ",
                    "tags": [
                        "Вашингтон"
                    ]
                }
            ]
        }   

## События матча [/game/{game_id}/text]
Получение текстовой трансляции матча - замены, голы, карточки 

### Трансляция матча [GET]
+ Argumnets
    + (Array)
        + (number) - минута матчка.
        + (number) - номер команды
        + (string) - тип события.
        + (string) - ФИО игрока.
        
+ Parameters
    + game_id: 12 (required, number) - ID команды integer

+ Response 200 (application/json)

        [
            [79,2,"SW","Набиль Эль-Жар","Давид Симон"],
            [76,2,"SW","Серхио Араухо","Тана Домингес"],
            [75,1,"SW","Джузеппе Росси","Жорди Шуметра"],
            [74,1,"YC","Жорди Шуметра"],
            [66,2,"GL","Виллиан Жозе"]
        ]

## Статистика [/game/{game_id}/stats]
Получение статистики о предыдущих играх команд

### Статистика [GET]
+ Argumnets
    + main: - основная статистика
        + (string) : (Array[2]) - заголовок строки : [значение хозеяв, значение для гостей]
    + groups: (Array) - дополнительная статистика
        + name: "Послдение игры Леванте" (string)  - название группы
        + type: (string) "tab" - тип группы. Может быть 3 типов - list,tabs и table 
        + tabs: (Array) - только если тип tab
            + name: "В сезоне"(string) - название таба
            + rows: (Array) - строки в табе
                + (Array[5]) - [id матча, дата, название команды 1, счет, название команды 2]
        +table: (Array) - только если тип table
            + (Array[10]) - [id команды, код страны, название команды, всего игр, выйграно, ничьи, проиграно, голов забито, голов пропущенно, очков]
+ Parameters
    + game_id: 12 (required, number) - ID команды integer

+ Response 200 (application/json)

        {
            "main":{
                "Матчей":[40,40],
                "Забитых мячей":[25,33],
                "Удары / в створ":["51/15","20/8"],
                "Угловые":[22,12]
            },
            "groups":[
                {
                    "name": "Послдение игры Леванте",
                    "type": "tab",
                    "tabs":[
                        {
                            "name":"В сезоне",
                            "rows":[
                                [123,"2016.01.05","Вестерн Сити","1:0","Леванте"],
                                [125,"2016.02.07","Леванте","3:2","Арсенал"],
                                [126,"2016.03.15","Арсенал","2:0","Леванте"],
                                [77,"2016.04.23","Вестерн Сити","3:1","Леванте"]
                            ]
                        },
                        {
                            "name":"В турнире",
                            "rows":[
                                [12,"2016.01.05","Вестерн Сити","1:0","Леванте"],
                                [23,"2016.02.07","Леванте","3:2","Арсенал"],
                                [56,"2016.03.15","Арсенал","2:0","Леванте"],
                                [18,"2016.04.23","Вестерн Сити","3:1","Леванте"]
                            ]
                        }
                    ]
                },
                {
                    "name": "Турнирная таблица",
                    "type": "table",
                    "table":[
                        [223,"ES","Вестерн Сити",16,9,3,4,16,9,30],
                        [125,"ES","Леванте",16,9,3,4,16,9,28],
                        [34,"ES","Арсенал",16,9,3,4,16,9,27],
                        [567,"ES","Вестерн Сити",16,9,3,4,16,9,20],
                        [12,"ES","Арсенал",16,9,3,4,16,9,19],
                        [67,"ES","Леванте Сити",16,9,3,4,16,9,6]
                    ]
                },
            ]
        }
        

## Составы [/game/{game_id}/list]
Информация о составах команд

### Состав [GET]
+ Arguments
    + coach - главный тренер.
        + home: (string) - тренер домашней команды
        + guest: (string) - тренер гостевой команды
    + in - Стартовые составы
        + home:(Array) - домашней команды - [ номер игрока, имя игрока, позиция]
        + guest:(Array) - гостевой команды - [ номер игрока, имя игрока, позиция]
    + substitution - Замены
        + home:(Array) - домашней команды - [ номер игрока, имя игрока, позиция]
        + guest:(Array) - гостевой команды - [ номер игрока, имя игрока, позиция]
    + injury - Травмированы / Точно не сыграют
        + home:(Array) - домашней команды - [ номер игрока, имя игрока, позиция]
        + guest:(Array) - гостевой команды - [ номер игрока, имя игрока, позиция]
    + Parameters
        + game_id: 12 (required, number) - ID команды integer
+ Значение позиции игроков:
    + C - Capitane ( капитан )
    + GK  - Goalkeeper ( вратарь )
    + SW  - Free Defender ( свободный защитник ) 
    + RB  - Right Defender ( правый защитник ) 
    + LB  - Left Defender ( левый защитник ) 
    + CB  - Central Defender ( центр защитник ) 
    + RWB  - Right Attacking Defender ( правый атакующий защитник ) 
    + LWB  - Left Attacking Defender ( левый атакующий защитник ) 
    + CDM  - Central Defensive Midfielder ( опорный/оборонительный полузащитник ) 
    + RM  - Right Midfielder ( правый полузащитник ) 
    + CM  - Central Midfielder ( центральный полузащитник ) 
    + LM  - Left Midfielder   ( левый полузащитник ) 
    + RWM  - Right Side Midfielder ( правый атакующий полузащитник ) 
    + LWM  -   Left Side Midfielder ( левый атакующий полузащитник ) 
    + CAM  - Central Attacking Midfielder ( центральный атакующий полузащитник ) 
    + RF  - Right Forward ( правый отянутый форвард ) 
    + CF  - Central Forward ( центральный отянутый форвард ) 
    + LF  - Left Forward ( левый отянутый форвард ) 
    + RS  - Right Striker ( правый конечный форвард ) 
    + LS  - Left Striker ( левый конечный форвард )
    + ST  - Striker ( центр форвард )
+ Parameters
    + game_id: 12 (required, number) - ID команды integer
    
+ Response 200 (application/json)

        {
            "coach":{
                "home":"Джузеппе Росси",
                "guest":"Серхио Араухо"
            },
            "in":{
                "home":[
                    [5,"Набиль Эль-Жар","C"],
                    [6,"Давид Симон","GK"],
                    [7,"Серхио Араухо","LB"],
                    [8,"Джузеппе Росси","LWM"],
                    [10,"Жорди Шуметра","RS"],
                    [2,"Виллиан Жозе","ST"]
                ],
                "guest":[
                    [5,"Набиль Эль-Жар","C"],
                    [6,"Давид Симон","GK"],
                    [7,"Серхио Араухо","CAM"],
                    [8,"Джузеппе Росси","CDM"],
                    [10,"Жорди Шуметра","CF"],
                    [2,"Виллиан Жозе","LS"]
                ]
            },
            "substitution":{
                "home":[
                    [5,"Набиль Эль-Жар","C"],
                    [6,"Давид Симон","GK"],
                    [7,"Серхио Араухо","ST"],
                    [8,"Джузеппе Росси","D"],
                    [10,"Жорди Шуметра","P"],
                    [2,"Виллиан Жозе","W"]
                ],
                "guest":[
                    [5,"Набиль Эль-Жар","CAM"],
                    [6,"Давид Симон","GK"],
                    [7,"Серхио Араухо","ST"],
                    [8,"Джузеппе Росси","D"],
                    [10,"Жорди Шуметра","GK"],
                    [2,"Виллиан Жозе","W"]
                ]
            },
            "injury":{
                "home":[
                    [5,"Набиль Эль-Жар","C"],
                    [6,"Давид Симон","GK"]
                ],
                "guest":[
                    [5,"Набиль Эль-Жар","C"]
                ]
            }
        }

## Ставки [/game/{game_id}/odds]
Информация о ставках и коэффициентах на матч от разных буккмекеров

### Ставки на матч [GET]
+ Arguments
    + P1: (Array) - Победа 1-ой команды - [ [ID букмекера, коэффициент букмекера] ].
    + Х: (Array) - Ничья - [ [ID букмекера, коэффициент букмекера] ]
    + Р2:  (Array) - Победа 2-ой команды - [ [ID букмекера, коэффициент букмекера] ]
    + 1Х: Победа 1-ой команды или ничья - [ [ID букмекера, коэффициент букмекера] ].
    + groups (Array) - группы ставок
        + name: Точный счет (string) - название группы
        ... остальные атрибуты строки в группе. Название атрибута - название строки, значение массив из  [ID букмекера, коэффициент букмекера] 
        Тотал больше/меньше = [ массив больше , массив меньше ]
    + books -  букмекеры
        + id: 12 (number) - ID букмекера 
        + name: FairPlay (string) - Имя букмекера
        + logo: //img.neverbet.com/img.neverbet.com/books/FairPlay.png (string) - ссылка на лого букмекера.
        
+ Parameters
    + game_id: 12 (required, number) - ID команды integer

+ Response 200 (application/json)

        {
            "P1": [[1,1.0],[2,1.1]],
            "X": [[1,1.0],[2,1.1]],
            "P2": [[1,1.0],[2,1.1]],
            "1X": [[1,1.0],[2,1.1]],
            "X2": [[1,1.0],[2,1.1]],
            "12": [[1,1.0],[2,1.1]],
            "groups":[
                {
                    "name": "Точный счет",
                    "1:0":[[1,2.1],[2,2.2],[3,1.8]],
                    "1:1":[[1,2.1],[2,1.6],[3,2.0]],
                    "2:0":[[1,2.1],[2,2.1]],
                    "1:2":[[1,2.1],[2,1.2]]
                },
                {
                    "name":"Больше/Меньше",
                    "0.5":[[[[1,1.0],[2,1.1]]],[[[1,1.0],[2,1.1]]]],
                    "1":[[[[1,1.0],[2,1.1]]],[[[1,1.0],[2,1.1]]]],
                    "1.5":[[[[1,1.0],[2,1.1]]],[[[1,1.0],[2,1.1]]]],
                },
                {
                    "name":"Тотал матча",
                    "Чет":[[[[1,1.0],[2,1.1]]],[[[1,1.0],[2,1.1]]]],
                    "Нечет":[[[[1,1.0],[2,1.1]]],[[[1,1.0],[2,1.1]]]]
                }
            ],
            "books":[
                {
                    "id":1,
                    "name":"Olimp",
                    "logo":"//img.neverbet.com/books/Olimp.png"
                },
                {
                    "id":2,
                    "name":"LEON",
                    "logo":"//img.neverbet.com/books/leon.png"
                },
                {
                    "id":3,
                    "name":"FairPlay",
                    "logo":"//img.neverbet.com/books/FairPlay.png"
                }
            ]
        }

## Чат [/game/{game_id}/chat]
Информация о чате матча

### Чат [GET]
+ Arguments
    + id: (number) -  ID чата матча
+ Parameters
    + game_id: 12 (required, number) - ID команды integer

+ Response 200 (application/json)

        {
            "id": 123
        }

## Голосование [/game/{game_id}/vote/{?type}]
Выбор лучшего или худшего игрока матча

### Список игроков [GET]
+ Arguments
    + home: (Array) -  игроки команды хозяев
        + (Array[3]) - [ID игрока, имя игрока, позиция игрока]
    + guest: (Array) - игроки команды гостей
        + (Array[3]) - [ID игрока, имя игрока, позиция игрока]
+ Parameters
    + game_id: 12 (required, number) - ID команды integer
    + type: "best" (required, string) - 2 типа "best" или "worst"

+ Response 200 (application/json)

        {
            "home":[
                [5,"Набиль Эль-Жар","C"],
                [6,"Давид Симон","GK"],
                [7,"Серхио Араухо","LB"],
                [8,"Джузеппе Росси","LWM"],
                [10,"Жорди Шуметра","RS"],
                [2,"Виллиан Жозе","ST"]
            ],
            "guest":[
                [5,"Набиль Эль-Жар","C"],
                [6,"Давид Симон","GK"],
                [7,"Серхио Араухо","CAM"],
                [8,"Джузеппе Росси","CDM"],
                [10,"Жорди Шуметра","CF"],
                [2,"Виллиан Жозе","LS"]
            ]
        }

### Проголосовать [POST]
+ Parameters
    + game_id: 12 (required, number) - ID команды integer
    + type: "best" (required, string) - 2 типа "best" или "worst"
    + id: 14 (required, number) - ID игрока integer

+ Response 200 (application/json)

        {
            "home":[
                [5,"Набиль Эль-Жар","C"],
                [6,"Давид Симон","GK"],
                [7,"Серхио Араухо","LB"],
                [8,"Джузеппе Росси","LWM"],
                [10,"Жорди Шуметра","RS"],
                [2,"Виллиан Жозе","ST"]
            ],
            "guest":[
                [5,"Набиль Эль-Жар","C"],
                [6,"Давид Симон","GK"],
                [7,"Серхио Араухо","CAM"],
                [8,"Джузеппе Росси","CDM"],
                [10,"Жорди Шуметра","CF"],
                [2,"Виллиан Жозе","LS"]
            ]
        }

# Group Команда

## Список команд [/teams]
Возвращает список команд по группам

### Список [GET]
+ Arguments
    + name: Национальные (string) - название группы.
    + groups: (Array) - список подгрупп
    + icon: "//img.neverbet.com/country/EN.png" (string) - адрес иконки группы
    + teams: (Array) - список команд в группе/подгруппе
        + id: 12 (number) - ID команды.
        + name: Барселона (string) - название команды на русском.
        + logo: //img.neverbet.com/mini/barcelona.png (string) - ссылка на лого команды.

+ Response 200 (application/json)

        [
            {
                "name": "Популярные",
                "teams":[
                    {
                        "id" : 12,
                        "name": "Барселона",
                        "logo": "//img.neverbet.com/team/mini/barcelona.png",
                    }
                ]
            },
            {
                "name": "Национальные",
                "groups":[
                    {
                        "name": "Англия",
                        "icon": "//img.neverbet.com/country/EN.png",
                        "teams":[
                            {
                                "id" : 12,
                                "name": "Барселона",
                                "logo": "//img.neverbet.com/team/mini/barcelona.png",
                            }
                        ]
                    }
                ]
            }
        ]
        
## Команда [/team/{team_id}]
Подробное описание команды

### Описание команды [GET]
+ Arguments
    + id: 12 (number) - ID команды.
    + name: Барселона (string) - название команды на русском.
    + original: Barcelona (string) - оригинальное название команды.
    + rating: 6.8 (number) - рейтинг команды.
    + country: ES (string len=2) - IATA код страны команды.
    + city: Барселона (string) - город в котором базируется команда.
    + coach: Луис Энрике (string) - тренер команда.
    + arena: Камп Ноу (string) - домашняя арена команды.
    + based: 1899.11.23 (Date) - дата основания команды в формате Y.m.d
    + logo: //img.neverbet.com/team/barcelona.png (string) - ссылка на лого команды.
    + status: WLDWW (string) - статистика по последним 5 играм. W (win) - побед,  L(lose) - поражений, D(draw) - ничьи.
    + stats: (Object) - статистика
        + name (string): value (string) - название : значение
    + games: (Array) - прошедшие 5 игр команды
        + id: 12 (number) - ID номер матча 
        + dtime: 2016.01.05 20:30 (DateTime) - дата и время начала матча в формате Y.m.d H:m 
        + home: Вестерн Сити (string) - название домашней команды 
        + score:(string) - счет в матче
        + guest: (string) - название команды гостей
    + feeds: (Array) - последние новости/публикации по команде
        + id: 12 (number) - ID номер публикации 
        + author: (Author) - автор публикации
            + type: owner (string) - тип авторства: owner - владелец, repost - перепубликации
            + id: 12 (number) - ID автора
            + rate: 33 (number) - рейтинг авторa
            + name: Костян Филатов (string) - имя автора
            + thumb: "//img.neverbet.com/thumb/u56.jpg" (string) - адрес к аватарке пользователя
        + dtime: 2016.01.05 20:30 (DateTime) - дата и время публикации в формате Y.m.d H:m 
        + comments: 12 (number) - кол-во комментариев к публикации
        + rate: 3 (number) - рейтинг публикации
        + body: (string) - сообщение
        + tags: (Array) - массив тегов к публикации
        
+ Parameters
    + team_id: 12 (required, number) - ID команды integer

+ Response 200 (application/json)

        [
            {
                "id" : 12,
                "name": "Барселона",
                "original": "Barcelona",
                "rating": 6.8,
                "country": "ES",
                "city": "Барселона",
                "coach": "Луис Энрике",
                "arena": "Камп Ноу",
                "based": "1899.11.23",
                "logo": "//img.neverbet.com/team/barcelona.png",
                "status": "WLDWW",
                "stats":{
                    "матчи": 32,
                    "гол / матч": 1.1,
                    "желтые карточки": 2,
                    "красные карточки": 3,
                    "угловые": 12
                },
                "games":[
                    {
                        "id":12,
                        "dtime": "2016.01.05 20:30",
                        "home":"Вестерн Сити",
                        "score":"1:0",
                        "guest":"Леванте"
                    }
                ],
                "feeds":[
                    {
                        "id": 1235,
                        "author":{
                            "type":"owner",
                            "id":56,
                            "rate":33,
                            "name":"Костян Филатов",
                            "thumb":"//img.neverbet.com/user/u56.jpg"
                        },
                        "dtime": "2016.01.05 20:30",
                        "comments":12,
                        "rate":3,
                        "body":"<img src='//img.neverbet.com/feeds/u56sdf23gf.jpg'/>Русский форвард #Вашингтона оформил 14-й хет-трик за карьеру в НХЛ",
                        "tags": [
                            "Вашингтон"
                        ]
                    }
                ]
            }   
        ]
        
## Новости [/team/{team_id}/feeds/{?offset}]
Новости/публикации по команде

### Новости команды [GET]
+ Arguments
    + id: 12 (number) - ID номер публикации 
    + author: (Author) - автор публикации
        + type: owner (string) - тип авторства: owner - владелец, repost - перепубликации
        + id: 12 (number) - ID автора
        + rate: 33 (number) - рейтинг авторa
        + name: Костян Филатов (string) - имя автора
        + thumb: "//img.neverbet.com/thumb/u56.jpg" (string) - адрес к аватарке пользователя
    + dtime: 2016.01.05 20:30 (DateTime) - дата и время публикации в формате Y.m.d H:m 
    + comments: 12 (number) - кол-во комментариев к публикации
    + rate: 3 (number) - рейтинг публикации
    + body: (string) - сообщение
    + tags: (Array) - массив тегов к публикации
    
+ Parameters
    + team_id: 12 (required, number) - ID команды integer
    + offset: 12 (number) - отступ для выборки

+ Response 200 (application/json)

        [
            {
                "id": 1235,
                "author":{
                    "type":"owner",
                    "id":56,
                    "rate":33,
                    "name":"Костян Филатов",
                    "thumb":"//img.neverbet.com/user/u56.jpg"
                },
                "dtime": "2016.01.05 20:30",
                "comments":12,
                "rate":3,
                "body":"<img src='//img.neverbet.com/feeds/u56sdf23gf.jpg'/>Русский форвард #Вашингтона оформил 14-й хет-трик за карьеру в НХЛ",
                "tags": [
                    "Вашингтон"
                ]
            }  
        ]
        
## Состав [/team/{team_id}/list]
Состав команды по группам

### Состав команды [GET]
+ Arguments
    + (string) : (Array) - название группы игроков
        + id: (number) - ID игрока
        + number:  (number) - игровой номер игрока
        + name: (string) - имя игрока
        + thumb: (string) - адрес к фото игрока
        + games: (number) - кол-во игр в которых принял участие игрок
        + goals: (number) - кол-во забитых голов 
        + missed: (number) - кол-во пропущенных голов

+ Parameters
    + team_id: 12 (required, number) - ID команды integer

+ Response 200 (application/json)

        {
            "Вратарь":[
                {
                    "id":22,
                    "number":7,
                    "name":"Эндрю Редмейн",
                    "thumb":"//img.neverbet.com/football/g22.jpg",
                    "games":16,
                    "goals":2,
                    "missed":0
                }
            ],
            "Защитник":[
                {
                    "id":23,
                    "number":6,
                    "name":"Брендан Хэмилл",
                    "thumb":"//img.neverbet.com/football/g22.jpg",
                    "games":16,
                    "goals":2,
                    "missed":0
                }
            ]
        }

## Таблица [/team/{team_id}/table/{?season}{?turnir_id}]
Турнирные таблицы турниров в которых принимает участие команда
Если не задан сезон и турнир, возвращает все турниры на данный сезон

### Турнирная таблица [GET]
+ Arguments
    + turnir: (Turnir) -
        + id: (number) - ID турнира
        + name: (string) - название турнира
        + country: (string) - IATA код страны
    + seasons: (Object) - список доступных сезонов
        + value: name - номер сезона / название сезона
    + season: (string) - название сезона
    + table: (Object)
        + name : (Array) - название таблицы
            + (Array[10]) - [id команды, код страны, название команды, всего игр, выйграно, ничьи, проиграно, голов забито, голов пропущенно, очков]
        

+ Parameters
    + team_id: 12 (required, number) - ID команды integer
    + season: 2016 (string) - сезон для выборки, передается год окончание сезона
    + turnir_id: 12 (number) - ID турнира

+ Response 200 (application/json)

        [
            {
               "turnir":{
                    "id":12,
                    "name": "Примьер Лига",
                    "country": "UK"
               },
               "seasons":{
                    "2012":"2011/2012",
                    "2015":"2014/2015",
                    "2016":"2015/2016",
                },
               "season":"2015/2016",
               "table":{
                    "Основная таблица":[
                        [223,"ES","Вестерн Сити",16,9,3,4,16,9,30],
                        [125,"ES","Леванте",16,9,3,4,16,9,28],
                        [34,"ES","Арсенал",16,9,3,4,16,9,27],
                        [567,"ES","Вестерн Сити",16,9,3,4,16,9,20],
                        [12,"ES","Арсенал",16,9,3,4,16,9,19],
                        [67,"ES","Леванте Сити",16,9,3,4,16,9,6]
                    ],
                    "Последние 5 туров":[
                        [223,"ES","Вестерн Сити",16,9,3,4,16,9,30],
                        [125,"ES","Леванте",16,9,3,4,16,9,28],
                        [34,"ES","Арсенал",16,9,3,4,16,9,27],
                        [567,"ES","Вестерн Сити",16,9,3,4,16,9,20],
                        [12,"ES","Арсенал",16,9,3,4,16,9,19],
                        [67,"ES","Леванте Сити",16,9,3,4,16,9,6]
                    ]
                }
            }
        ]
        
## Матчи [/team/{team_id}/games/{?season}{?turnir_id}]
Матчи в которых команда принимает/принимала участие

### Матчи [GET]
+ Arguments
    + turnirs: (Object)  - список доступных турниров
        + value: name - номер турнира / название турнира
    + seasons: (Object) - список доступных сезонов
        + value: name - номер сезона / название сезона
    + games: (Array) - список игр
        + id: 11 (number) - ID матча.
        + dtime: 2016.02.05 20:00:00 (DateTime) - время проведения матча в формате YY.mm.dd H:m:s (? timezone UTC).
        + status: wait (string) - wait, live, cancel, fin
        + info:
            + score: 3-2 (string) - счет матча
            + part: 2 (number) - тайм
            + minute: 86 (number) - минута матча
        + home: (Team) - первая команда
            + id: 22 (number) - ID команды.
            + name: Барселона (string) - название команды на русском.
            + logo: //img.neverbet.com/barcelona.png (string) -  ссылка на лого команды.
            + country: ES (string len=2) - IATA код страны команды.
            + cards - карточки
                + yellow: 2 (number) - желтые карты
                + red: 0 (number) - красные карты
            + corners: 2  (number) - угловые
        + guest: (Team) - вторая команда
            + id: 21 (number) - ID команды.
            + name: Рома (string) - название команды на русском.
            + logo: //img.neverbet.com/roma.png (string) -  ссылка на лого команды.
            + country: IT (string len=2) - IATA код страны команды.
            + cards - карточки
                + yellow: 2 (number) - желтые карты
                + red: 0 (number) - красные карты
            + corners: 2  (number) - угловые
        + odds - ставки / коэффициенты
            + P1 : 1.2 (float) - победа первой команды 
            + X: 2.2 (float) - ничья 
            + P2: 2.0 (float) - победа второй команды 
            + TOTAL: (Object)  - тотал
                "2.5": (Array[2]) - значение [больше чем значение, меньше чем значение] 
    
+ Parameters
    + team_id: 12 (required, number) - ID команды integer
    + season: 2016 (string) - сезон для выборки, передается год окончание сезона
    + turnir_id: 12 (number) - ID турнира

+ Response 200 (application/json)

        [
            "seasons":{
                "2012":"2011/2012",
                "2015":"2014/2015",
                "2016":"2015/2016",
            },
            "turnirs":{
                123:"Испания. Примера",
                12:"Чемпионат Испании"
            },
            "games":[
                {
                    "id": 11,
                    "dtime": "2016.02.05 20:00:00",
                    "status" : "live",
                    "info":{
                        "score": "3-0",
                        "part": 2,
                        "minute": 86
                    },
                    "home":{
                        "id": 22,
                        "name": "Барселона",
                        "country": "ES",
                        "cards":{
                            "yellow":2,
                            "red":0
                        },
                        "corners": 2
                    },
                    "guest": {
                        "id":21,
                        "name": "Рома",
                        "country": "ES",
                        "cards":{
                            "yellow":4,
                            "red":1
                        },
                        "corners": 12
                    },
                    "odds":{
                        "P1": 1.2,
                        "X": 2.2,
                        "P2": 2.0,
                        "TOTAL": {
                            "2.5":[1.2,3.2]
                        }
                }
            ]
        ]
        
# Group Турниры

## Список турниров [/turnirs]
Возвращает список турниров по группам

### Список [GET]
+ Arguments
    + name: (string) - название группы.
    + groups: (Array) - список подгрупп
    + icon: (string) - адрес иконки группы
    + turnirs: (Array) - список турниров в группе/подгруппе
        + id: (number) - ID турнира.
        + name: (string) - название турнира на русском.
        + icon: (string) - адрес иконки турнира

+ Response 200 (application/json)

        [
            {
                "name": "Популярные",
                "turnirs":[
                    {
                        "id" : 12,
                        "name": "Примьер-Лига",
                        "icon": "//img.neverbet.com/country/EN.png"
                    }
                ]
            },
            {
                "name": "Национальные",
                "groups":[
                    {
                        "name": "Англия",
                        "icon": "//img.neverbet.com/country/EN.png",
                        "turnirs":[
                            {
                                "id" : 12,
                                "name": "Примьер-Лига",
                                "icon": "//img.neverbet.com/country/EN.png",
                            },
                            {
                                "id" : 13,
                                "name": "Чемпионшип",
                                "icon": "//img.neverbet.com/country/EN.png",
                            }
                        ]
                    }
                ]
            }
        ]
        
## Турнир [/turnir/{turnir_id}]
Подробное описание туринира

### Описание туринира [GET]
+ Arguments
    + id: (number) - ID турнира
    + name: (string) - название турнира на русском.
    + descr: (string) - описание турнира
    + country: (string len=2) - IATA код страны турнира 
    + logo: (string) - ссылка на лого турнира.
    + feeds: (Array) - последние новости/публикации по турниру
        + id: 12 (number) - ID номер публикации 
        + author: (Author) - автор публикации
            + type: owner (string) - тип авторства: owner - владелец, repost - перепубликации
            + id: 12 (number) - ID автора
            + rate: 33 (number) - рейтинг авторa
            + name: Костян Филатов (string) - имя автора
            + thumb: "//img.neverbet.com/thumb/u56.jpg" (string) - адрес к аватарке пользователя
        + dtime: 2016.01.05 20:30 (DateTime) - дата и время публикации в формате Y.m.d H:m 
        + comments: 12 (number) - кол-во комментариев к публикации
        + rate: 3 (number) - рейтинг публикации
        + body: (string) - сообщение
        + tags: (Array) - массив тегов к публикации
        
+ Parameters
    + turnir_id: 12 (required, number) - ID туринира 

+ Response 200 (application/json)

        [
            {
                "id" : 12,
                "name": "Премьер-Лига",
                "descr": "Чемпионат Англии по футболу",
                "country": "EN",
                "logo": "//img.neverbet.com/turnir/enpremier.png",
                "feeds":[
                    {
                        "id": 1235,
                        "author":{
                            "type":"owner",
                            "id":56,
                            "rate":33,
                            "name":"Костян Филатов",
                            "thumb":"//img.neverbet.com/user/u56.jpg"
                        },
                        "dtime": "2016.01.05 20:30",
                        "comments":12,
                        "rate":3,
                        "body":"<img src='//img.neverbet.com/feeds/u56sdf23gf.jpg'/>Русский форвард #Вашингтона оформил 14-й хет-трик за карьеру в НХЛ",
                        "tags": [
                            "Вашингтон"
                        ]
                    }
                ]
            }   
        ]
        
## Новости [/turnir/{turnir_id}/feeds/{?offset}]
Новости/публикации по турниру

### Новости турнира [GET]
+ Arguments
    + id: 12 (number) - ID номер публикации 
    + author: (Author) - автор публикации
        + type: owner (string) - тип авторства: owner - владелец, repost - перепубликации
        + id: 12 (number) - ID автора
        + rate: 33 (number) - рейтинг авторa
        + name: Костян Филатов (string) - имя автора
        + thumb: "//img.neverbet.com/thumb/u56.jpg" (string) - адрес к аватарке пользователя
    + dtime: 2016.01.05 20:30 (DateTime) - дата и время публикации в формате Y.m.d H:m 
    + comments: 12 (number) - кол-во комментариев к публикации
    + rate: 3 (number) - рейтинг публикации
    + body: (string) - сообщение
    + tags: (Array) - массив тегов к публикации
    
+ Parameters
    + turnir_id: 12 (required, number) - ID турнира
    + offset: 12 (number) - отступ для выборки

+ Response 200 (application/json)

        [
            {
                "id": 1235,
                "author":{
                    "type":"owner",
                    "id":56,
                    "rate":33,
                    "name":"Костян Филатов",
                    "thumb":"//img.neverbet.com/user/u56.jpg"
                },
                "dtime": "2016.01.05 20:30",
                "comments":12,
                "rate":3,
                "body":"<img src='//img.neverbet.com/feeds/u56sdf23gf.jpg'/>Русский форвард #Вашингтона оформил 14-й хет-трик за карьеру в НХЛ",
                "tags": [
                    "Вашингтон"
                ]
            }  
        ]
        
## Таблица [/turnir/{turnir_id}/table/{?season}]
Турнирная таблица. Если не задан сезон, таблицу на данный сезон

### Турнирная таблица [GET]
+ Arguments
    + seasons: (Object) - список доступных сезонов
        + value: name - номер сезона / название сезона
    + season: (string) - название сезона
    + table: (Object)
        + name : (Array) - название таблицы
            + (Array[10]) - [id команды, код страны, название команды, всего игр, выйграно, ничьи, проиграно, голов забито, голов пропущенно, очков]
        

+ Parameters
    + turnir_id: 12 (required, number) - ID команды integer
    + season: 2016 (string) - сезон для выборки, передается год окончание сезона

+ Response 200 (application/json)

        [
            {
               "seasons":{
                    "2012":"2011/2012",
                    "2015":"2014/2015",
                    "2016":"2015/2016",
                },
               "season":"2015/2016",
               "table":{
                    "Основная таблица":[
                        [223,"ES","Вестерн Сити",16,9,3,4,16,9,30],
                        [125,"ES","Леванте",16,9,3,4,16,9,28],
                        [34,"ES","Арсенал",16,9,3,4,16,9,27],
                        [567,"ES","Вестерн Сити",16,9,3,4,16,9,20],
                        [12,"ES","Арсенал",16,9,3,4,16,9,19],
                        [67,"ES","Леванте Сити",16,9,3,4,16,9,6]
                    ],
                    "Последние 5 туров":[
                        [223,"ES","Вестерн Сити",16,9,3,4,16,9,30],
                        [125,"ES","Леванте",16,9,3,4,16,9,28],
                        [34,"ES","Арсенал",16,9,3,4,16,9,27],
                        [567,"ES","Вестерн Сити",16,9,3,4,16,9,20],
                        [12,"ES","Арсенал",16,9,3,4,16,9,19],
                        [67,"ES","Леванте Сити",16,9,3,4,16,9,6]
                    ]
                }
            }
        ]
        
## Матчи [/turnir/{turnir_id}/games/{?season}{?tour_id}]
Матчи в турнире

### Матчи [GET]
+ Arguments
    + tours: (Object)  - список доступных турниров
        + value: name - номер тура / название тура
    + seasons: (Object) - список доступных сезонов
        + value: name - номер сезона / название сезона
    + games: (Array) - список игр
        + id: 11 (number) - ID матча.
        + dtime: 2016.02.05 20:00:00 (DateTime) - время проведения матча в формате YY.mm.dd H:m:s (? timezone UTC).
        + status: wait (string) - wait, live, cancel, fin
        + info:
            + score: 3-2 (string) - счет матча
            + part: 2 (number) - тайм
            + minute: 86 (number) - минута матча
        + home: (Team) - первая команда
            + id: 22 (number) - ID команды.
            + name: Барселона (string) - название команды на русском.
            + logo: //img.neverbet.com/barcelona.png (string) -  ссылка на лого команды.
            + country: ES (string len=2) - IATA код страны команды.
            + cards - карточки
                + yellow: 2 (number) - желтые карты
                + red: 0 (number) - красные карты
            + corners: 2  (number) - угловые
        + guest: (Team) - вторая команда
            + id: 21 (number) - ID команды.
            + name: Рома (string) - название команды на русском.
            + logo: //img.neverbet.com/roma.png (string) -  ссылка на лого команды.
            + country: IT (string len=2) - IATA код страны команды.
            + cards - карточки
                + yellow: 2 (number) - желтые карты
                + red: 0 (number) - красные карты
            + corners: 2  (number) - угловые
        + odds - ставки / коэффициенты
            + P1 : 1.2 (float) - победа первой команды 
            + X: 2.2 (float) - ничья 
            + P2: 2.0 (float) - победа второй команды 
            + TOTAL: (Object)  - тотал
                "2.5": (Array[2]) - значение [больше чем значение, меньше чем значение] 
    
+ Parameters
    + turnir_id: 12 (required, number) - ID команды integer
    + season: 2016 (string) - сезон для выборки, передается год окончание сезона
    + tour_id: 12 (number) - ID турнира

+ Response 200 (application/json)

        [
            "seasons":{
                "2012":"2011/2012",
                "2015":"2014/2015",
                "2016":"2015/2016",
            },
            "tours":{
                123:"1-ый тур",
                12:"2-ой тур"
            },
            "games":[
                {
                    "id": 11,
                    "dtime": "2016.02.05 20:00:00",
                    "status" : "live",
                    "info":{
                        "score": "3-0",
                        "part": 2,
                        "minute": 86
                    },
                    "home":{
                        "id": 22,
                        "name": "Барселона",
                        "country": "ES",
                        "cards":{
                            "yellow":2,
                            "red":0
                        },
                        "corners": 2
                    },
                    "guest": {
                        "id":21,
                        "name": "Рома",
                        "country": "ES",
                        "cards":{
                            "yellow":4,
                            "red":1
                        },
                        "corners": 12
                    },
                    "odds":{
                        "P1": 1.2,
                        "X": 2.2,
                        "P2": 2.0,
                        "TOTAL": {
                            "2.5":[1.2,3.2]
                        }
                }
            ]
        ]
        
# Group Лента

## Лента [/feeds/{?offset}]
Подробное описание туринира

### Публикации [GET]
+ Arguments
    + id: 12 (number) - ID номер публикации 
    + author: (Author) - автор публикации
        + type: owner (string) - тип авторства: owner - владелец, repost - перепубликации
        + id: 12 (number) - ID автора
        + rate: 33 (number) - рейтинг авторa
        + name: Костян Филатов (string) - имя автора
        + thumb: "//img.neverbet.com/thumb/u56.jpg" (string) - адрес к аватарке пользователя
    + dtime: 2016.01.05 20:30 (DateTime) - дата и время публикации в формате Y.m.d H:m 
    + comments: 12 (number) - кол-во комментариев к публикации
    + rate: 3 (number) - рейтинг публикации
    + body: (string) - сообщение
    + tags: (Array) - массив тегов к публикации
        
+ Parameters
    + offset: 12 (number) - отступ для выборки

+ Response 200 (application/json)

        [
            {
                "id": 1235,
                "author":{
                    "type":"owner",
                    "id":56,
                    "rate":33,
                    "name":"Костян Филатов",
                    "thumb":"//img.neverbet.com/user/u56.jpg"
                },
                "dtime": "2016.01.05 20:30",
                "comments":12,
                "rate":3,
                "body":"<img src='//img.neverbet.com/feeds/u56sdf23gf.jpg'/>Русский форвард #Вашингтона оформил 14-й хет-трик за карьеру в НХЛ",
                "tags": [
                    "Вашингтон"
                ]
            }
        ]
        
## Публикация [/feed]
Подробное описание Публикации

### Подбробнее о публикации [GET /feed/{id}]
+ Arguments
    + id: 12 (number) - ID номер публикации 
    + author: (Author) - автор публикации
        + type: owner (string) - тип авторства: owner - владелец, repost - перепубликации
        + id: 12 (number) - ID автора
        + rate: 33 (number) - рейтинг авторa
        + name: Костян Филатов (string) - имя автора
        + thumb: "//img.neverbet.com/thumb/u56.jpg" (string) - адрес к аватарке пользователя
    + dtime: 2016.01.05 20:30 (DateTime) - дата и время публикации в формате Y.m.d H:m 
    + comments: 12 (number) - кол-во комментариев к публикации
        + id: 12 (number) - ID комментария
        + author: (Author) - автор публикации
            + id: 12 (number) - ID автора
            + rate: 33 (number) - рейтинг авторa
            + name: Костян Филатов (string) - имя автора
            + thumb: "//img.neverbet.com/thumb/u56.jpg" (string) - адрес к аватарке пользователя
        + dtime: 2016.01.05 20:30 (DateTime) - дата и время публикации в формате Y.m.d H:m 
        + body: (string) - комментарий
    + rate: 3 (number) - рейтинг публикации
    + body: (string) - сообщение
    + tags: (Array) - массив тегов к публикации
        
+ Parameters
    + id: 12 (required, number) - ID публикации 

+ Response 200 (application/json)

        {
            "id": 1235,
            "author":{
                "type":"owner",
                "id":56,
                "rate":33,
                "name":"Костян Филатов",
                "thumb":"//img.neverbet.com/user/u56.jpg"
            },
            "dtime": "2016.01.05 20:30",
            "comments":[
                {
                    "id": 1235,
                    "author":{
                        "id":56,
                        "rate":33,
                        "name":"Костян Филатов",
                        "thumb":"//img.neverbet.com/user/u56.jpg"
                    },
                    "dtime": "2016.01.05 20:30",
                    "body":"Думаю сейчас ставить на Примеру...Есть идеи?"
                }
            ],
            "rate":3,
            "body":"<img src='//img.neverbet.com/feeds/u56sdf23gf.jpg'/>Русский форвард #Вашингтона оформил 14-й хет-трик за карьеру в НХЛ",
            "tags": [
                "Вашингтон"
            ]
        }

### Написать публикацию [POST /feed]
Если публикация содержит изображения/видео необходимо загружать их отдельным запросом.

+ Arguments
    + auth: (string) - тип приватности публикации public/folowers/friends/private
    + body: (string) - текстовое сообщение публикации
    + tags: (Array) - массив текстовых тегов
    
+ Request (application/json)

    + Body

            {
                "auth": "public",
                "body": "<img src='//img.neverbet.com/feeds/u56sdf23gf.jpg'/>Русский форвард #Вашингтона оформил 14-й хет-трик за карьеру в НХЛ",
                "tags": [
                    "Вашингтон"
                ]
            }
    
+ Response 204

### Редактировать публикацию [PUT /feed/{id}]
Если публикация содержит изображения/видео необходимо загружать их отдельным запросом.

+ Parameters
    + id: 12 (required, number) - ID публикации 

+ Request (application/json)

    + Body

            {
                "body": "<img src='//img.neverbet.com/feeds/u56sdf23gf.jpg'/>Русский форвард #Вашингтона оформил 14-й хет-трик за карьеру в НХЛ",
                "tags": [
                    "Вашингтон"
                ]
            }
    
+ Response 204

### Удалить публикацю [DELETE /feed/{id}]

+ Parameters
    + id: 12 (required, number) - ID публикации 

+ Response 204

## Комментарии [/feed/{id}/comments]
Комментарии к Публикации

### Комментарии [GET /feed/{id}/comments]
+ Arguments
    + id: 12 (number) - ID номер публикации 
    + author: (Author) - автор публикации
        + id: 12 (number) - ID автора
        + rate: 33 (number) - рейтинг авторa
        + name: Костян Филатов (string) - имя автора
        + thumb: "//img.neverbet.com/thumb/u56.jpg" (string) - адрес к аватарке пользователя
    + dtime: 2016.01.05 20:30 (DateTime) - дата и время публикации в формате Y.m.d H:m 
    + body: (string) - сообщение
        
+ Parameters
    + id: 12 (required, number) - ID публикации 

+ Response 200 (application/json)

        [
                {
                    "id": 1235,
                    "author":{
                        "id":56,
                        "rate":33,
                        "name":"Костян Филатов",
                        "thumb":"//img.neverbet.com/user/u56.jpg"
                    },
                    "dtime": "2016.01.05 20:30",
                    "body":"Думаю сейчас ставить на Примеру...Есть идеи?"
                }
        ]

### Написать публикацию [POST /feed/{id}/comments]

+ Parameters
    + id: 12 (required, number) - ID публикации 

+ Request (application/json)

    + Body

            {
                "body": "Думаю сейчас ставить на Примеру...Есть идеи?"
            }
    
+ Response 204

### Удалить публикацю [DELETE /comments/{id}]

+ Parameters
    + id: 12 (required, number) - ID комментария 

+ Response 204



# Group Рейтинг букмекеров

## Рейтинг [/books]
Рейтинг букмекеров

### Рейтинг [GET]
+ Arguments
    + id:  (number) - ID букмекера 
    + name: (string) - Имя букмекера
    + logo: (string) - ссылка на лого букмекера.
    + comments: (number) - кол-во отзывов
    + rate: (string) - рейтинг букмекера

+ Response 200 (application/json)

        [
            {
                "id": 1235,
                "name": "Olimp",
                "logo":"//img.neverbet.com/books/olimp.png",
                "comments":957,
                "rate":"A",
            }
        ]
        
## Профайл [/books/{id}]
Профайл букмекерa

### Профайл букмекерa[GET]
+ Arguments
    + id:  (number) - ID букмекера 
    + name: (string) - Имя букмекера
    + logo: (string) - ссылка на лого букмекера.
    + rate: (string) - рейтинг букмекера
    + about: (string) - описание конторы
    + rules: (Array) - массив групп правил
        + name:descr - название группы правил : описание правил
    
+ Parameters
    + id: 12 (required, number) - ID букмекера 
    
+ Response 200 (application/json)

        {
            "id": 1235,
            "name": "Olimp",
            "logo":"//img.neverbet.com/books/olimp.png",
            "rate":"A",
            "about":"Надежная букмекерская контора. Предлагает одну из самых широких линий для ставок на футбол"
            "rules":{
                "Ввод/вывод денежных средств":"Очень быстрый расчет ставок, сразу после определения результата."
            }
        }
        
## Отзывы [/books/{id}/reviews{?offset}]
Отзывы букмекерa

### Отзывы[GET]
+ Arguments
    + id: 12 (number) - ID номер отзыва 
    + author: (Author) - автор публикации
        + id: 12 (number) - ID автора
        + rate: 33 (number) - рейтинг авторa
        + name: Костян Филатов (string) - имя автора
        + thumb: "//img.neverbet.com/thumb/u56.jpg" (string) - адрес к аватарке пользователя
    + dtime: 2016.01.05 20:30 (DateTime) - дата и время отзыва в формате Y.m.d H:m 
    + body: (string) - сообщение
    
+ Parameters
    + id: 12 (required, number) - ID букмекера 
    + offset: 12 (number) - отступ для выборки
    
+ Response 200 (application/json)

        [
                {
                    "id": 1235,
                    "author":{
                        "id":56,
                        "rate":33,
                        "name":"Костян Филатов",
                        "thumb":"//img.neverbet.com/user/u56.jpg"
                    },
                    "dtime": "2016.01.05 20:30",
                    "body":"<img src='//img.neverbet.com/feeds/u56sdf23gf.jpg'/>Русский форвард #Вашингтона оформил 14-й хет-трик за карьеру в НХЛ"
                }
        ]

### Создать отзыв [POST /books/{id}/reviews]
+ Arguments
    + body: (string) - сообщение
    + tags: (Array) - массив тегов к публикации

+ Parameters
    + id: 12 (required, number) - ID букмеккера 
    
+ Request (application/json)

    + Body

            {
                "body":"<img src='//img.neverbet.com/feeds/u56sdf23gf.jpg'/>Русский форвард #Вашингтона оформил 14-й хет-трик за карьеру в НХЛ",
                "tags": [
                    "Вашингтон"
                ]
            }

+ Response 201

        {
                "id": 1235,
                "author":{
                    "type":"owner",
                    "id":56,
                    "rate":33,
                    "name":"Костян Филатов",
                    "thumb":"//img.neverbet.com/user/u56.jpg"
                },
                "dtime": "2016.01.05 20:30",
                "comments":0,
                "rate":0,
                "body":"<img src='//img.neverbet.com/feeds/u56sdf23gf.jpg'/>Русский форвард #Вашингтона оформил 14-й хет-трик за карьеру в НХЛ",
                "tags": [
                    "Вашингтон"
                ]
        }

### Редактировать отзыв [PUT /books/{id}/reviews/{post_id}]
+ Arguments
    + body: (string) - сообщение
    + tags: (Array) - массив тегов к публикации

+ Parameters
    + id: 12 (required, number) - ID букмеккера 
    + post_id: 12 (required, number) - ID публикации
    
+ Request (application/json)

    + Body

            {
                "body":"<img src='//img.neverbet.com/feeds/u56sdf23gf.jpg'/>Русский форвард #Вашингтона оформил 14-й хет-трик за карьеру в НХЛ",
                "tags": [
                    "Вашингтон"
                ]
            }

+ Response 202

        {
                "id": 1235,
                "author":{
                    "type":"owner",
                    "id":56,
                    "rate":33,
                    "name":"Костян Филатов",
                    "thumb":"//img.neverbet.com/user/u56.jpg"
                },
                "dtime": "2016.01.05 20:30",
                "comments":0,
                "rate":0,
                "body":"<img src='//img.neverbet.com/feeds/u56sdf23gf.jpg'/>Русский форвард #Вашингтона оформил 14-й хет-трик за карьеру в НХЛ",
                "tags": [
                    "Вашингтон"
                ]
        }


### Удалить отзыв [DELETE /books/{id}/reviews/{post_id}]

+ Parameters
    + id: 12 (required, number) - ID букмеккера
    + post_id: 12 (required, number) - ID публикации

+ Response 204

## Бонусы [/books/{id}/bonus{?offset}]
Бонусы букмекерa

### Бонусы[GET]
+ Arguments
    + name: (string) - заголовок
    + body: (string) - описание бонуса
    
+ Parameters
    + id: 12 (required, number) - ID букмекера 
    + offset: 12 (number) - отступ для выборки
    
+ Response 200 (application/json)

        [
            {
                "name":"Бонус до 10% на экспресс",
                "body":"<img src='//img.neverbet.com/books/bonus1.jpg'/>K каждой экспресс-ставке от 2 до 10%, с шагом 1% за каждое событие в экспрессе. При этом Что нужно знать о бонусах букмекеровучитываются события с коэффициентом от 2.5 и выше. Акция не распространяется на ставки Live."
            }
        ]

# Group Лига Прогнозов

## Турниры [/league]
Список турниров в лиге прогнозистов

### Список [GET]
+ Arguments
    + id:  (number) - ID турнира 
    + name: (string) - название турнира
    + logo: (string) - лого турнира.
    + members: (number) - кол-во участников
    + descr: (string) - описание турнира
    + prize: (string) - призовой фонд
    + finish: (DateTime) - дата и время окончания тура Y.m.d H:m

+ Response 200 (application/json)

        [
            {
                "id": 1235,
                "name": "Царь горы",
                "logo":"//img.neverbet.com/league/1.png",
                "descr":"7 удачных прогнозов подряд сделают вас обладателем 5 000 рублей, и этот приз можно получить неоднократно. Количество попыток неограниченно!",
                "prize":"5000p",
                "members":1200,
                "finish":"2016.01.05 20:30"
            }
        ]
        
## Турнир [/league/{id}]
Описание правил турнира

### Турнир[GET]
+ Arguments
    + about: (string) - описание турнира
    + rules: (Array) - массив групп правил
        + name:descr - название группы правил : описание правил
    
+ Parameters
    + id: 12 (required, number) - ID турнира 
    
+ Response 200 (application/json)

        {
            "about":"Надежная букмекерская контора. Предлагает одну из самых широких линий для ставок на футбол"
            "rules":{
                "Ввод/вывод денежных средств":"Очень быстрый расчет ставок, сразу после определения результата."
            }
        }
        
## Победители турнира [/league/{id}/winners]
Список победителей турнира по турам

### Турнир[GET]
+ Arguments
    + name: Костян Филатов (string) - имя автора
    + winners: (Array) - массив победителей
        + id: 12 (number) - ID автора
        + rate: 33 (number) - рейтинг авторa
        + name: Костян Филатов (string) - имя автора
        + thumb: "//img.neverbet.com/thumb/u56.jpg" (string) - адрес к аватарке пользователя
    
+ Parameters
    + id: 12 (required, number) - ID турнира 
    
+ Response 200 (application/json)

        [
            {
                "name":"Тур №5",
                "winners":[
                    {
                        "id":56,
                        "rate":33,
                        "name":"Костян Филатов",
                        "thumb":"//img.neverbet.com/user/u56.jpg"
                    }
                ]
            }
        ]
        
## Вопросы турнира [/league/{id}/questions]
Список вопросов турнира. Вариантов ответа на вопрос может быть более 3х

### Вопросы[GET]
+ Arguments
    + id: 12 (number) - ID автора
    + turnir: (Object)
        + id: (number) - ID турнира.
        + name: (string) - название турнира
        + country: (string) - код страны
    + game: (Object)
        + id: 11 (number) - ID матча.
        + dtime: 2016.02.05 20:00:00 (DateTime) - время проведения матча в формате YY.mm.dd H:m:s (? timezone UTC).
        + status: wait (string) - wait, live, cancel, fin
        + info:
            + score: 3-2 (string) - счет матча
            + part: 2 (number) - тайм
            + minute: 86 (number) - минута матча
        + home: (Team) - первая команда
            + id: 22 (number) - ID команды.
            + name: Барселона (string) - название команды на русском.
            + logo: //img.neverbet.com/barcelona.png (string) -  ссылка на лого команды.
            + country: ES (string len=2) - IATA код страны команды.
            + cards - карточки
                + yellow: 2 (number) - желтые карты
                + red: 0 (number) - красные карты
            + corners: 2  (number) - угловые
        + guest: (Team) - вторая команда
            + id: 21 (number) - ID команды.
            + name: Рома (string) - название команды на русском.
            + logo: //img.neverbet.com/roma.png (string) -  ссылка на лого команды.
            + country: IT (string len=2) - IATA код страны команды.
            + cards - карточки
                + yellow: 2 (number) - желтые карты
                + red: 0 (number) - красные карты
            + corners: 2  (number) - угловые
    + question: (string) - текст вопроса
    + answers: (Object) - варинаты ответа
        + номер ответа : заголовок
    
+ Parameters
    + id: 12 (required, number) - ID турнира 
    
+ Response 200 (application/json)

        [
            {
                "id":56,
                "turnir":{
                    "id":33,
                    "name":"Примера",
                    "country": "ES"
                },
                "game":{
                    "id": 11,
                    "dtime": "2016.02.05 20:00:00",
                    "status" : "live",
                    "info":{
                        "score": "3-0",
                        "part": 2,
                        "minute": 86
                    },
                    "home":{
                        "id": 22,
                        "name": "Барселона",
                        "country": "ES",
                        "cards":{
                            "yellow":2,
                            "red":0
                        },
                        "corners": 2
                    },
                    "guest": {
                        "id":21,
                        "name": "Рома",
                        "country": "ES",
                        "cards":{
                            "yellow":4,
                            "red":1
                        },
                        "corners": 12
                    }
                },
                "question":"Победит Барселона?",
                "answers":{
                    "1":"Победит",
                    "2":"Ничья",
                    "3":"Нет"
                }
            }
        ]
        
### Выбрать ответ на вопрос [POST /league/{id}/questions]
+ Arguments
    + номер вопроса : номер ответа
    
+ Parameters
    + id: 12 (required, number) - ID турнира 

+ Request (application/json)

    + Body

            {
                "56": 1,
                "58": 2
            }
    
+ Response 201

# Group Избранное

## Матчи [/favorite/games]
Список избранных матчей пользователя

### Список [GET]
+ Arguments
    + id: 11 (number) - ID матча.
    + dtime: 2016.02.05 20:00:00 (DateTime) - время проведения матча в формате YY.mm.dd H:m:s (? timezone UTC).
    + status: wait (string) - wait, live, cancel, fin
    + info:
        + score: 3-2 (string) - счет матча
        + part: 2 (number) - тайм
        + minute: 86 (number) - минута матча
    + home: (Team) - первая команда
        + id: 22 (number) - ID команды.
        + name: Барселона (string) - название команды на русском.
        + logo: //img.neverbet.com/barcelona.png (string) -  ссылка на лого команды.
        + country: ES (string len=2) - IATA код страны команды.
        + cards - карточки
            + yellow: 2 (number) - желтые карты
            + red: 0 (number) - красные карты
        + corners: 2  (number) - угловые
    + guest: (Team) - вторая команда
        + id: 21 (number) - ID команды.
        + name: Рома (string) - название команды на русском.
        + logo: //img.neverbet.com/roma.png (string) -  ссылка на лого команды.
        + country: IT (string len=2) - IATA код страны команды.
        + cards - карточки
            + yellow: 2 (number) - желтые карты
            + red: 0 (number) - красные карты
        + corners: 2  (number) - угловые
+ Response 200 (application/json)

        [
            {
               "id": 11,
                "dtime": "2016.02.05 20:00:00",
                "status" : "live",
                "info":{
                    "score": "3-0",
                    "part": 2,
                    "minute": 86
                },
                "home":{
                "id": 22,
                    "name": "Барселона",
                    "country": "ES",
                    "cards":{
                        "yellow":2,
                            "red":0
                    },
                    "corners": 2
                },
                "guest": {
                    "id":21,
                    "name": "Рома",
                    "country": "ES",
                    "cards":{
                        "yellow":4,
                        "red":1
                    },
                "corners": 12
            }
        ]

### Добавить в избронное [POST /favorite/games/{id}]

+ Parameters
    + id: 12 (required, number) - ID матча 

+ Response 202

### Удалить  [DELETE /favorite/games/{id}]

+ Parameters
    + id: 12 (required, number) - ID матча 

+ Response 204



## Турниры [/favorite/turnirs]
Список избранных турниров пользователя

### Список [GET]
+ Arguments
    + id: (number) - ID турнира.
    + name: (string) - название турнира на русском.
    + icon: (string) - адрес иконки турнира

+ Response 200 (application/json)

        [
            {
                "id" : 12,
                "name": "Примьер-Лига",
                "icon": "//img.neverbet.com/country/EN.png"
            }
        ]

### Добавить в избронное [POST /favorite/turnirs/{id}]

+ Parameters
    + id: 12 (required, number) - ID турнира 

+ Response 202

### Удалить  [DELETE /favorite/turnirs/{id}]

+ Parameters
    + id: 12 (required, number) - ID турнира 

+ Response 204


## Команды [/favorite/teams]
Список избранных команд пользователя

### Список [GET]
+ Arguments
    + id: (number) - ID команды.
    + name: (string) - название команды на русском.
    + icon: (string) - адрес иконки команды

+ Response 200 (application/json)

        [
            {
                "id" : 12,
                "name": "Барселона",
                "icon": "//img.neverbet.com/team/barcelona.png"
            }
        ]

### Добавить в избронное [POST /favorite/teams/{id}]

+ Parameters
    + id: 12 (required, number) - ID команды 

+ Response 202

### Удалить  [DELETE /favorite/teams/{id}]

+ Parameters
    + id: 12 (required, number) - ID команды 

+ Response 204

## Закладки [/favorite/feeds]
Список избранных пользователем публикаций

### Список [GET /favorite/feeds{?offset}]
+ Arguments
    + id: 12 (number) - ID номер публикации 
    + author: (Author) - автор публикации
        + type: owner (string) - тип авторства: owner - владелец, repost - перепубликации
        + id: 12 (number) - ID автора
        + rate: 33 (number) - рейтинг авторa
        + name: Костян Филатов (string) - имя автора
        + thumb: "//img.neverbet.com/thumb/u56.jpg" (string) - адрес к аватарке пользователя
    + dtime: 2016.01.05 20:30 (DateTime) - дата и время публикации в формате Y.m.d H:m 
    + comments: 12 (number) - кол-во комментариев к публикации
    + rate: 3 (number) - рейтинг публикации
    + body: (string) - сообщение
    + tags: (Array) - массив тегов к публикации
        
+ Parameters
    + offset: 12 (number) - отступ для выборки

+ Response 200 (application/json)

        [
            {
                "id": 1235,
                "author":{
                    "type":"owner",
                    "id":56,
                    "rate":33,
                    "name":"Костян Филатов",
                    "thumb":"//img.neverbet.com/user/u56.jpg"
                },
                "dtime": "2016.01.05 20:30",
                "comments":12,
                "rate":3,
                "body":"<img src='//img.neverbet.com/feeds/u56sdf23gf.jpg'/>Русский форвард #Вашингтона оформил 14-й хет-трик за карьеру в НХЛ",
                "tags": [
                    "Вашингтон"
                ]
            }
        ]
### Добавить в избронное [POST /favorite/feeds/{id}]

+ Parameters
    + id: 12 (required, number) - ID публикации 

+ Response 202

### Удалить  [DELETE /favorite/feeds/{id}]

+ Parameters
    + id: 12 (required, number) - ID публикации 

+ Response 204


# Group Группы

## Список Групп [/groups]
Список групп пользователя

### Список [GET]
+ Arguments
    + invites: (Array) - список рекомендуемых групп
        + id:  (number) - ID группы.
        + type: (string) - тип приватности группы public / private
        + name:  (string) - название группы на русском.
        + logo: //img.neverbet.com/groups/11.png (string) -  ссылка на лого группы.
    + groups:  (Array) - список групп ползователя
        + id:  (number) - ID группы.
        + type: (string) - тип приватности группы public / private
        + name: (string) - название группы на русском.
        + logo: //img.neverbet.com/groups/11.png (string) -  ссылка на лого группы.

+ Response 200 (application/json)

        [
            {
                "invites":[
                    {
                        "id": 11,
                        "type": "public",
                        "name": "Барселона",
                        "logo": "//img.neverbet.com/groups/11.jpg"
                    }
                ],
                "groups":[
                    {
                        "id": 11,
                        "type": "public",
                        "name": "Барселона",
                        "logo": "//img.neverbet.com/groups/11.jpg"
                    }
                ]
            }
        ]
### Создать группу [POST /groups]
+ Arguments
    + type: (string) - тип приватности группы public / private
    + name: (string) - название группы на русском.

+ Request (application/json)

    + Body

            {
                "type": "public",
                "name": "Барселона"
            }

+ Response 201


### Редактировать группу [PUT /groups/{id}]
+ Arguments
    + type: (string) - тип приватности группы public / private
    + name: (string) - название группы на русском.

+ Parameters
    + id: 12 (required, number) - ID группы 
    
+ Request (application/json)

    + Body

            {
                "type": "public",
                "name": "Барселона"
            }

+ Response 202


### Удалить  [DELETE /groups/{id}]

+ Parameters
    + id: 12 (required, number) - ID группы 

+ Response 204

## Группа [/group]
Подробнее о группе

### Группа [GET /group/{id}]
+ Arguments
        + id: 21 (number) - ID группы.
        + type: (string) - тип приватности группы public / private
        + name: Рома (string) - название группы на русском.
        + logo: //img.neverbet.com/groups/11.png (string) -  ссылка на лого группы.
        + stats: (Array)
            + string:number - название : значение
        + feeds: (Array)
            + id: 12 (number) - ID номер публикации 
            + author: (Author) - автор публикации
                + type: owner (string) - тип авторства: owner - владелец, repost - перепубликации
                + id: 12 (number) - ID автора
                + rate: 33 (number) - рейтинг авторa
                + name: Костян Филатов (string) - имя автора
                + thumb: "//img.neverbet.com/thumb/u56.jpg" (string) - адрес к аватарке пользователя
            + dtime: 2016.01.05 20:30 (DateTime) - дата и время публикации в формате Y.m.d H:m 
            + comments: 12 (number) - кол-во комментариев к публикации
            + rate: 3 (number) - рейтинг публикации
            + body: (string) - сообщение
            + tags: (Array) - массив тегов к публикации

+ Parameters
    + id: 12 (required, number) - ID группы 
    
+ Response 200 (application/json)

        {
            "id": 11,
            "type": "public",
            "name": "Барселона",
            "logo": "//img.neverbet.com/groups/11.jpg",
            "stats":{
                "участника":404,
                "обсуждений":4134,
                "фото":125
            },
            "feeds":[
                {
                    "id": 1235,
                    "author":{
                        "type":"owner",
                        "id":56,
                        "rate":33,
                        "name":"Костян Филатов",
                        "thumb":"//img.neverbet.com/user/u56.jpg"
                    },
                    "dtime": "2016.01.05 20:30",
                    "comments":12,
                    "rate":3,
                    "body":"<img src='//img.neverbet.com/feeds/u56sdf23gf.jpg'/>Русский форвард #Вашингтона оформил 14-й хет-трик за карьеру в НХЛ",
                    "tags": [
                        "Вашингтон"
                    ]
                }
            ]
        }
        
### Вступить в группу [POST /group/{id}]

+ Parameters
    + id: 12 (required, number) - ID группы 
    
+ Response 202


### Выйти из группы  [DELETE /group/{id}]

+ Parameters
    + id: 12 (required, number) - ID группы 

+ Response 202

## Публикации группы [/group/{id}/feeds]
Список публикаций в группе

### Публикации [GET /group/{id}/feeds{?offset}]
+ Arguments
        + feeds: (Array)
            + id: 12 (number) - ID номер публикации 
            + author: (Author) - автор публикации
                + type: owner (string) - тип авторства: owner - владелец, repost - перепубликации
                + id: 12 (number) - ID автора
                + rate: 33 (number) - рейтинг авторa
                + name: Костян Филатов (string) - имя автора
                + thumb: "//img.neverbet.com/thumb/u56.jpg" (string) - адрес к аватарке пользователя
            + dtime: 2016.01.05 20:30 (DateTime) - дата и время публикации в формате Y.m.d H:m 
            + comments: 12 (number) - кол-во комментариев к публикации
            + rate: 3 (number) - рейтинг публикации
            + body: (string) - сообщение
            + tags: (Array) - массив тегов к публикации

+ Parameters
    + id: 12 (required, number) - ID группы 
    + offset: 10 (number) - отступ для выборки
    
+ Response 200 (application/json)

        [
            {
                "id": 1235,
                "author":{
                    "type":"owner",
                    "id":56,
                    "rate":33,
                    "name":"Костян Филатов",
                    "thumb":"//img.neverbet.com/user/u56.jpg"
                },
                "dtime": "2016.01.05 20:30",
                "comments":12,
                "rate":3,
                "body":"<img src='//img.neverbet.com/feeds/u56sdf23gf.jpg'/>Русский форвард #Вашингтона оформил 14-й хет-трик за карьеру в НХЛ",
                "tags": [
                    "Вашингтон"
                ]
            }
        ]
### Создать запись [POST /group/{id}/feeds]
+ Arguments
    + body: (string) - сообщение
    + tags: (Array) - массив тегов к публикации

+ Parameters
    + id: 12 (required, number) - ID группы 
    
+ Request (application/json)

    + Body

            {
                "body":"<img src='//img.neverbet.com/feeds/u56sdf23gf.jpg'/>Русский форвард #Вашингтона оформил 14-й хет-трик за карьеру в НХЛ",
                "tags": [
                    "Вашингтон"
                ]
            }

+ Response 201

        {
                "id": 1235,
                "author":{
                    "type":"owner",
                    "id":56,
                    "rate":33,
                    "name":"Костян Филатов",
                    "thumb":"//img.neverbet.com/user/u56.jpg"
                },
                "dtime": "2016.01.05 20:30",
                "comments":0,
                "rate":0,
                "body":"<img src='//img.neverbet.com/feeds/u56sdf23gf.jpg'/>Русский форвард #Вашингтона оформил 14-й хет-трик за карьеру в НХЛ",
                "tags": [
                    "Вашингтон"
                ]
        }

### Редактировать запись [PUT /group/{id}/feeds/{post_id}]
+ Arguments
    + body: (string) - сообщение
    + tags: (Array) - массив тегов к публикации

+ Parameters
    + id: 12 (required, number) - ID группы 
    + post_id: 12 (required, number) - ID публикации
    
+ Request (application/json)

    + Body

            {
                "body":"<img src='//img.neverbet.com/feeds/u56sdf23gf.jpg'/>Русский форвард #Вашингтона оформил 14-й хет-трик за карьеру в НХЛ",
                "tags": [
                    "Вашингтон"
                ]
            }

+ Response 202

        {
                "id": 1235,
                "author":{
                    "type":"owner",
                    "id":56,
                    "rate":33,
                    "name":"Костян Филатов",
                    "thumb":"//img.neverbet.com/user/u56.jpg"
                },
                "dtime": "2016.01.05 20:30",
                "comments":0,
                "rate":0,
                "body":"<img src='//img.neverbet.com/feeds/u56sdf23gf.jpg'/>Русский форвард #Вашингтона оформил 14-й хет-трик за карьеру в НХЛ",
                "tags": [
                    "Вашингтон"
                ]
        }


### Удалить запись [DELETE /group/{id}/feeds/{post_id}]

+ Parameters
    + id: 12 (required, number) - ID группы
    + post_id: 12 (required, number) - ID публикации

+ Response 204


# Group Друзья

## Список друзей [/friends]
Список друзей пользователя

### Список [GET]
+ Arguments
    + invites: (Array) - список рекомендуемых друзей
        + id: 12 (number) - ID автора
        + rate: 33 (number) - рейтинг авторa
        + name: Костян Филатов (string) - имя автора
        + thumb: "//img.neverbet.com/thumb/u56.jpg" (string) - адрес к аватарке пользователя
        + bets: (number) - кол-во ставок
        + rating: (number) - рейтинг 
    + friends:  (Array) - список друзей ползователя
        + id: 12 (number) - ID автора
        + rate: 33 (number) - рейтинг авторa
        + name: Костян Филатов (string) - имя автора
        + thumb: "//img.neverbet.com/thumb/u56.jpg" (string) - адрес к аватарке пользователя
        + bets: (number) - кол-во ставок
        + rating: (number) - рейтинг 

+ Response 200 (application/json)

        [
            {
                "invites":[
                    {
                        "id":56,
                        "rate":33,
                        "name":"Костян Филатов",
                        "thumb":"//img.neverbet.com/user/u56.jpg",
                        "bets": 56,
                        "rating":815
                    }
                ],
                "friends":[
                    {
                        "id":56,
                        "rate":33,
                        "name":"Костян Филатов",
                        "thumb":"//img.neverbet.com/user/u56.jpg",
                        "bets": 56,
                        "rating":815
                    }
                ]
            }
        ]
### Добавить/Пригласить в друзья [POST /friends/{id}]
+ Parameters
    + id: 12 (required, number) - ID ползователя 
    
+ Response 201


### Удалить из друзей  [DELETE /friends/{id}]

+ Parameters
    + id: 12 (required, number) - ID ползователя 

+ Response 204

# Group Профайл игрока

## Профайл [/gamer/{id}]
Подробная информация о игроке

### Профайл [GET]
+ Arguments
    + id: 12 (number) - ID автора
    + country: (string) - страна
    + city: (string) - город
    + rate: 33 (number) - рейтинг авторa
    + name: Костян Филатов (string) - имя автора
    + thumb: "//img.neverbet.com/thumb/u56.jpg" (string) - адрес к аватарке пользователя
    + bets: (number) - кол-во ставок
    + rating: (number) - рейтинг 
    + friends: (number) - кол-во друзей
    + followers: (number) - кол-во подписчиков
    + status: (string) - последние 5 ставок игрока W (win), L (lose), D (draw)
    + stats: (Array) - 
        + name: (string) - название вида спорта
        + win: (number) - кол-во побед
        + total: (number) - общее кол-во игр
        + turnirs: (Array) - статистика по турнирам
            + name: (string) - название турнира
            + icon: (string) - адрес к иконке турнира
            + win: (number) - кол-во побед
            + lost: (number) - кол-во поражений


+ Parameters
    + id: 12 (required, number) - ID ползователя 

+ Response 200 (application/json)

        {
            "id":56,
            "rate":33,
            "name":"Костян Филатов",
            "thumb":"//img.neverbet.com/user/u56.jpg",
            "bets": 56,
            "rating":815,
            "friends":10,
            "followers":180,
            "status":"WLWDW",
            "stats":[
                {
                    "name":"Футбол",
                    "win":13,
                    "total":20,
                    "turnirs":[
                        {
                            "name":"Примера",
                            "icon":,"//img.neverbet.com/country/ES.png",
                            "win":13,
                            "lost":5
                        }
                    ]
                }
            ]
        }

### Подписаться [POST /gamer/{id}]
+ Parameters
    + id: 12 (required, number) - ID ползователя 
    
+ Response 201


### Отписаться [DELETE /gamer/{id}]

+ Parameters
    + id: 12 (required, number) - ID ползователя 

+ Response 204

## Рейтинг [/gamer/{id}/rating{?type}{?offset}]
Рейтинг игрока

### Рейтинг [GET]
+ Arguments
    + id: 12 (number) - ID автора
    + rate: 33 (number) - рейтинг авторa
    + name: Костян Филатов (string) - имя автора
    + thumb: "//img.neverbet.com/thumb/u56.jpg" (string) - адрес к аватарке пользователя
    + bets: (number) - кол-во ставок
    + wins: (number) - кол-во  побед
    + lost: (number) - кол-во поражений
    + rating: (number) - рейтинг 

+ Parameters
    + id: 12 (required, number) - ID ползователя 
    + type: friends (string) - global / friends
    + offset: 10 (number) - отступ для выборки

+ Response 200 (application/json)

        [
            {
                "id": 56,
                "rate": 33,
                "name": "Костян Филатов",
                "thumb": "//img.neverbet.com/user/u56.jpg",
                "bets": 56,
                "wins": 23,
                "lost": 5,
                "rating": 815
            }
        ]

## Ставки [/gamer/{id}/odds{?offset}]
Ставки игрока

### Ставки [GET]
+ Arguments
    + id: (number) - ID ставки
    + dtime: (DateTime) - время и дата ставки
    + options: события
        + id: (number) - ID ставки
        + status: (string) - статус ставки
        + name: (string) - заголов ставки
        + descr: (string) - текстовое описание ставки
        + ratio: (number) - коэф ставки
    + price: (number) - сумма ставки
    + ratio: (number) - общий коэф ставок

+ Parameters
    + id: 12 (required, number) - ID ползователя 
    + offset: 10 (number) - отступ для выборки

+ Response 200 (application/json)

        [
            {
                "id": 56,
                "dtime": "2016.05.15 12:22:13",
                "options":[
                    {
                        "id":32452,
                        "status":"wait",
                        "name":"Арсенал - Барселона",
                        "descr":"Исход победа первой",
                        "ratio":3.3
                    }
                ],
                "price":10000,
                "ratio":8.33
            }
        ]
        
## Стена [/gamer/{id}/feeds{?offset}]
Стена игрока

### Стена [GET]
+ Arguments
    + id: 12 (number) - ID номер публикации 
    + author: (Author) - автор публикации
        + type: owner (string) - тип авторства: owner - владелец, repost - перепубликации
        + id: 12 (number) - ID автора
        + rate: 33 (number) - рейтинг авторa
        + name: Костян Филатов (string) - имя автора
        + thumb: "//img.neverbet.com/thumb/u56.jpg" (string) - адрес к аватарке пользователя
    + dtime: 2016.01.05 20:30 (DateTime) - дата и время публикации в формате Y.m.d H:m 
    + comments: 12 (number) - кол-во комментариев к публикации
    + rate: 3 (number) - рейтинг публикации
    + body: (string) - сообщение
    + tags: (Array) - массив тегов к публикации

+ Parameters
    + id: 12 (required, number) - ID группы 
    + offset: 10 (number) - отступ для выборки
    
+ Response 200 (application/json)

        [
            {
                "id": 1235,
                "author":{
                    "type":"owner",
                    "id":56,
                    "rate":33,
                    "name":"Костян Филатов",
                    "thumb":"//img.neverbet.com/user/u56.jpg"
                },
                "dtime": "2016.01.05 20:30",
                "comments":12,
                "rate":3,
                "body":"<img src='//img.neverbet.com/feeds/u56sdf23gf.jpg'/>Русский форвард #Вашингтона оформил 14-й хет-трик за карьеру в НХЛ",
                "tags": [
                    "Вашингтон"
                ]
            }
        ]

# Group Ставки

## Ставки [/odds]
Ставки пользователя

### Список ставок [GET /odds{?offset}]
+ Arguments
    + total: (number) - всего ставок
    + ingame: (number) - сумма в игре
    + possible: (number) - возможный выйгрыш
    + win: (number) - выйграно
    + odds: (Array) - ставки
        + id: (number) - ID ставки
        + dtime: (DateTime) - время и дата ставки
        + options: события
            + id: (number) - ID ставки
            + status: (string) - статус ставки
            + name: (string) - заголов ставки
            + descr: (string) - текстовое описание ставки
            + ratio: (number) - коэф ставки
        + price: (number) - сумма ставки
        + ratio: (number) - общий коэф ставок

+ Parameters
    + offset: 10 (number) - отступ для выборки

+ Response 200 (application/json)

        {
            "total":23,
            "ingame":33000,
            "possible":145000,
            "win":45000,
            "odds":[
                {
                    "id": 56,
                    "dtime": "2016.05.15 12:22:13",
                    "options":[
                        {
                            "id":32452,
                            "status":"wait",
                            "name":"Арсенал - Барселона",
                            "descr":"Исход победа первой",
                            "ratio":3.3
                        }
                    ],
                    "price":10000,
                    "ratio":8.33
                }
            ]
        }

### Создать ставку [POST /odds]
+ Arguments
    + body: (string) - сообщение
    + tags: (Array) - массив тегов к публикации

+ Request (application/json)

    + Body

            {
                "body":"<img src='//img.neverbet.com/feeds/u56sdf23gf.jpg'/>Русский форвард #Вашингтона оформил 14-й хет-трик за карьеру в НХЛ",
                "tags": [
                    "Вашингтон"
                ]
            }

+ Response 201


### Удалить ставку  [DELETE /friends/{id}]

+ Parameters
    + id: 12 (required, number) - ID ползователя 

+ Response 204