FORMAT: 1A
HOST: http://polls.neverbet.kz/

# NeverBet

Документация по API 

## Список матчей [/games/{?date}]

+ turnir: 
    + id: 21 (number) - ID турнира.
    + name: Примера (string) - название турнира
    + country: ES (string) - страна турнира
+ games:
    + id: 11 (number) - ID матча.
    + time: 2016.02.05 20:00:00 (date) - время проведения матча в формате YY.mm.dd H:m:s (? timezone UTC).
    + status: wait (string) - wait, live, cancel, fin
    + info:
        + score: 3-2 (string) - счет матча
        + part: 2 (number) - тайм
        + minute: 86 (number) - минута матча
    + home:  - первая команда
        + id: 22 (number) - ID команды.
        + name: Барселона (string) - название команды на русском.
        + logo: //img.neverbet.kz/barcelona.png (string) -  ссылка на лого команды.
        + country: ES (string len=2) - IATA код страны команды.
        + cards - карточки
            + yellow: 2 (number) - желтые карты
            + red: 0 (number) - красные карты
        + corners: 2  (number) - угловые
    + guest:  - вторая команда
        + id: 21 (number) - ID команды.
        + name: Рома (string) - название команды на русском.
        + logo: //img.neverbet.kz/roma.png (string) -  ссылка на лого команды.
        + country: IT (string len=2) - IATA код страны команды.
        + cards - карточки
            + yellow: 2 (number) - желтые карты
            + red: 0 (number) - красные карты
        + corners: 2  (number) - угловые

### Список матчей [GET]
+ Parameters
    + date: 2016.04.15 (optional, string) - ID команды integer
+ Response 200 (application/json)

        [
            {
                "turnir": {
                    "id": 1,
                    "name": "Примера",
                    "country": "ES"
                },
                "games":[
                    {
                        "id": 11,
                        "time": "2016-02-05 20:00:00",
                        "status" : "live",
                        "info":{
                            "score": "3-0",
                            "part": 2,
                            "minute": 86
                        },
                        "home":{
                            "id": 22,
                            "name": "Барселона",
                            "country": "ES",
                            "cards":{
                                "yellow":2,
                                "red":0
                            },
                            "corners": 2
                        },
                        "guest": {
                            "id":21,
                            "name": "Рома",
                            "country": "ES",
                            "cards":{
                                "yellow":4,
                                "red":1
                            },
                            "corners": 12
                        }
                    }
                ]
            }   
        ]

## Команда [/team/{team_id}]

+ id: 12 (number) - ID команды.
+ name: Барселона (string) - название команды на русском.
+ translit: barcelona (string) - транслит команды для URL.
+ country: ES (string len=2) - IATA код страны команды.
+ logo: //img.neverbet.kz/barcelona.png (string) - ссылка на лого команды.

### Описание команды [GET]
+ Parameters
    + team_id: 12 (required, number) - ID команды integer

+ Response 200 (application/json)

        [
            {
                "id" : 12,
                "name": "Барселона",
                "translit": "barselona",
                "country": "ES",
                "logo": "//img.neverbet.kz/barcelona.png",
            }   
        ]